config/routes.rb
AriakeBook::Application.routes.draw do
  get "static_pages/home"

  resources :users, only:[:new, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :entries
  resources :bookmarks

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/bookmark', to: 'bookmarks#new'
  match '/destroy', to: 'bookmarks#destroy', via: :delete
  match '/add', to: 'bookmarks#add_bookmark'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  attr_accessible :comment, :entry_id, :user_id
  belongs_to :entry

  validates :entry_id, presence: true
  validates :user_id, presence: true
end

app/models/bookmarks.rb
require 'open-uri'
class Bookmarks < ActiveRecord::Base
  attr_accessible :comment, :entry_id, :user_id
  belongs_to :entry

  validates :entry_id, presence: true
  validates :user_id, presence: true
 
end

app/models/entry.rb
require 'open-uri'
require 'nkf'
class Entry < ActiveRecord::Base
  attr_accessible :url, :title
  before_save :fetch_title

  def fetch_title
    html = open(self.url).read
    match = html.match(/<title>(.*)<\/title>/i)
    self.title = NKF.nkf("-m0 -w", match[1])
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :id, :lastupdate, :name, :password,:password_confirmation
  has_secure_password

  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  validates :password, presence: true
  validates :password_confirmation, presence: true

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/bookmarks_controller.rb
# -*- coding: utf-8 -*-
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end
  
  def new
    @entry = Entry.find(params[:entry_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(params[:bookmark])
    @a = Bookmark.where(:user_id => @bookmark.user_id) 
    @data = @a.find_by_entry_id(@bookmark.entry.id)
    if !@data
      if @bookmark.save
        redirect_to root_path
      end
    else
      flash[:message] = "既にブックマークしているよ "
      redirect_to root_path
    end
  end

  def show
    @bookmarks = Bookmark.find(params)
    @entry = @bookmarks.entry
  end

  def add_bookmark
    @entry = Entry.new
  end
  
  def destroy
   @bookmark = Bookmark.find(params[:id])
   @bookmark.destroy
   redirect_to root_path
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  
  def new
    @entry = Entry.new
  end
  
  def create
    @entry = Entry.new(params[:entry])
    @data = Entry.find_by_url(@entry.url)
    if @data
      @entry = @data
    else
      @entry.save
    end   
    redirect_to "/bookmark?entry_id=#{@entry.id}"
  end
  
  def show
    @entry = Entry.find(params[:id])
  end

  def index
    @e = Entry.all
    @entries = @e.order("id DESC")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by_name(params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      #redirect_back_or user
      redirect_to root_path
    else
      # Create an error message and re-render the signin form.
      flash[:error] = 'Invalid name/password combination' # Not quite right!    
      redirect_to root_path
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = User.new
    @e = Entry.order("created_at DESC")
    @entries = @e
    
    if signed_in?
       @bookmarks = Bookmark.where("user_id = ?", current_user.id).order("created_at DESC")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

     respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    
    respond_to do |format|
      if @user.save
        sign_in @user
        flash[:loginsuccess] = 'User was successfully created.'
        format.html { redirect_to root_path  } 
        format.json { render json: @user, status: :created, location: @user }
      else
        #flash[:error] = @user.errors.full_messages
        format.html { render 'new' }#redirect_to :back}
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis
  def full_title(page_title)
    base_title = "Game Bookmark"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end
  
  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end
  
  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.fullpath
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_bookmark.html.erb
<h3><%= link_to bookmark.entry.title ,bookmark.entry.url, :target =>["_blank"] %></h3>
<ul>
  <li><%= bookmark.comment %></li>
  <li><%= link_to '削除', bookmark, confirm: '消すよ？', method: :delete %></li>
</ul>

app/views/bookmarks/add_bookmark.html.erb
<%= provide(:title, '') %>
<% if signed_in? %>

  <h1>ブックマークを追加する</h1>
  <div class="add">
  <%= form_for(@entry,:html=>{:class=>"field_add",:id=>nil}) do |f| %>
    
    <%= f.text_field :url,:size=>60,:class=>"text" %>
    <%= f.submit "追加",class:"submit" %>
    
  <% end %>
  <p>URLを入力して、追加ボタンを押して下さい</p>
  </div>		 
<% end %>

<div id="footer">
Copyright (C) 有明三日目. All Rights Reserved.　
</div>

app/views/bookmarks/index.html.erb
<%= render @bookmarks %>

app/views/bookmarks/new.html.erb
<%= provide(:title, '' ) %>
<h1>コメントを追加する</h1>
<div class="add">
  <%= form_for(@bookmark,:html=>{:class=>"field_add",:id=>nil}) do |f| %>

    <%= hidden_field_tag "bookmark[entry_id]" , params[:entry_id] %>
    <%= hidden_field_tag "bookmark[user_id]" , current_user.id %>
    <h3><%= @entry.title  %></h3>
    <%= f.text_field :comment,:size=>60,:class=>"text"%>
    <%= f.submit "追加",class:"submit" %>

  <% end %>
</div>

app/views/entries/_entry.html.erb
<h3><%= link_to entry.title, entry.url, :target=>["_blank"] %></h3>
<ul>
  <li><%= entry.url %></li>
</ul>

app/views/entries/index.html.erb
<%= render @entries %>

app/views/entries/show.html.erb
<section>
 <h1><%= @entry.title %></h1>
 <h2><%= @entry.url % ></h2>
</section>

app/views/layouts/_header.html.erb
<div id="header">
  <div id="header-inner">
    <div id="logo">
    <%=image_tag("gbm_logo.png",:size=>"330x50",:alt=>"gbm_logo")%>
    </div>
    <div id="header_navi">
      <ul id="list_header">
        <% if signed_in? %>
         <li><%= link_to "Home", root_path %></li>
         <li><%= link_to "Add", '/add' %></li>
        <% end %>
        <li><% if signed_in? %>
       <%= link_to "Sign out", signout_path, method: "delete" %>　
      <% end %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
  <%= render 'layouts/header' %>
  <div id="container">
    <% flash.each do |key, value| %>
       <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>

  </div>

  
</body>
</html>

app/views/static_pages/home.html.erb
<%= provide(:title, '') %>
<% if signed_in? %>

  <h1><%= current_user.name %>さんのページ</h1>
  <!-- Begin Left Column -->
  <div id="my_bookmark">
    <h2>new entry</h2>
    <%= render @entries %>
  </div>
  <!-- End Left Column -->
		 
  <!-- Begin Right Column -->
  <div id="new_entry">
    <h2>my bookmark</h2>
    <%= render @bookmarks %>		 
  </div>
  <!-- End Right Column -->

<% else %>
  <h1>ようこそGame Bookmarkへ！</h1>
  <p>
  Gamebookmarkは、ゲーム情報を集めたソーシャルブックマークです。<br />
  見てればなんとなくいいかんじにゲームの情報が手に入ります。
  </p>
 <section>
   <%= render :template => 'sessions/new' %>
 </section>
   <%= form_for(@user) do |f| %>
     <%= render :template => 'users/new' %>
   <% end %>
<% end %>

<div id="footer">
Copyright (C) 有明三日目. All Rights Reserved.　
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name ,class:"text" %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password ,class:"text" %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation ,class:"text"%>
  </div>
  
  <div class="actions">
    <%= f.submit "新規作成",class:"submit" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= provide(:title, 'Edit!') %>
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= provide(:title, 'All User!') %>
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Lastupdate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.lastupdate %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="sign"> 
  <h2>新規登録して下さい</h2>

  <%= form_for(@user) do |f| %>
    <%= render :template => 'users/_form' %>
  <% end %>

</div>

app/views/users/show.html.erb
<%= provide(:title, 'User Page!') %>
<p>
ようこそ<%= @user.name %>さん
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>